subscribers:
  camera_reading:
    topic: /camera/image
    queue_size: 1

publishers:
  bounding_boxes:
    topic: /darknet_ros/coco/bounding_boxes
    queue_size: 1
    latch: false

  detection_image:
    topic: /darknet_ros/coco/detection_image
    queue_size: 1
    latch: true

image_view:
  enable_opencv: true
  wait_key_delay: 1
  enable_console_output: true
